languageCode = "en-us"
title = "TBNL"
theme = "hugo-steam-theme"
paginate = 10
enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[markup.goldmark.renderer]
unsafe= true