baseurl = "https://www.dev.tibobeijen.nl/"
languageCode = "en-us"
title = "TBNL"
theme = "hugo-steam-theme"
paginate = 10

[taxonomies]
tag = "tags"
category = "categories"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
