
title = "TBNL"
subtitle = "…another view on the web and how it’s built"
copyright = "Released under the MIT license."

# You can choose between green, orange, red and blue.
themeColor = "tbnl-btbam-p2fs"

# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""

# To provide some metadata for search engines and the about section in the footer
# feel free to add a few information about you and your website.
name = "Tibo Beijen"
author = "Tibo Beijen"
bio = "DevOps, Python, JS lead-developer/architect. UX enthusiast. Coffee addict. Loud music aficionado. Dad. Runner. AFOL. Opinions own."
description = "DevOps and programming related personal blog of Tibo Beijen"
location = ""                                                                                                                              # optional
twitter = "TBeijen"
linkedin = 'tibobeijen'
mastodon = 'hachyderm.io/@tbeijen'
googleplus = ''
facebook = ''
instagram = ''
github = "TBeijen"
gitlab = ""
bitbucket = ""

# Enable a comment system
# You can choose between Disqus or Google Plus by setting comments
# to disqus or googleplus. For using Disqus you need to enter your
# shortname in disqusShortname at the top of the configs. 
comments = ""

# By setting homeMaxPosts, home page will show limited number of post and link to archive (/post/) 
# instead of paginated list of posts
homeMaxPosts = 5

# Use summary instead, if description is empty
useSummaryIfNoDescription = true

# Customize or translate the strings
archiveStr = "Older posts"
keepReadingStr = "Keep reading"
backtotopStr = "Back to top"
shareStr = "Share"
pageNotFoundTitle = "404 - Page not found"

# Set to true to block index (meta tag & robots.txt)
blockIndex = true
