baseurl = "https://www.dev.tibobeijen.nl/"
languageCode = "en-us"
title = "TBNL"
theme = "hugo-steam-theme"
# disqusShortname = "tibobeijen-nl"
paginate = 10

[taxonomies]
tag = "tags"
category = "categories"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]

	title = "TBNL"
	subtitle = "…another view on the web and how it’s built"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "tbnl-btbam-p2fs"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = "UA-6241889-1"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Tibo Beijen"
	bio = "Python, JS and DevOps developer (not limited to). UX enthusiast. Coffee addict. Loud music aficionado."
	description = "DevOps and programming related personal blog"
	location = "" # optional
	twitter = "TBeijen"
 	linkedin = 'tibobeijen'
 	googleplus = ''
 	facebook = ''
 	instagram = ''
	github = "TBeijen"
 	gitlab = ""
	bitbucket = ""

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# By setting homeMaxPosts, home page will show limited number of post and link to archive (/post/) 
	# instead of paginated list of posts
	homeMaxPosts = 3

	# Use summary instead, if description is empty
	useSummaryIfNoDescription = true

	# Customize or translate the strings
	archiveStr = "Older posts"
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
